apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brigade-metrics.exporter.fullname" . }}
  labels:
    {{- include "brigade-metrics.labels" . | nindent 4 }}
    {{- include "brigade-metrics.exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ .Values.exporter.brigade.apiToken }}
