apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brigade-metrics.exporter.fullname" . }}
  labels:
    {{- include "brigade-metrics.labels" . | nindent 4 }}
    {{- include "brigade-metrics.exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.exporter.brigade.apiToken }}
  brigadeAPIToken: {{ .Values.exporter.brigade.apiToken }}
  {{- else }}
    {{ fail "Value MUST be specified for exporter.brigade.apiToken" }}
  {{- end }}
