apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "brigade-metrics.prometheus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "brigade-metrics.labels" . | nindent 4 }}
    {{- include "brigade-metrics.prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      external_labels:
        monitor: 'codelab-monitor'

    scrape_configs:
    - job_name: 'node-exporter'

      # Override the global default and scrape targets from this job every 5 seconds.
      scrape_interval: {{ .Values.prometheus.scrapeInterval }}

      static_configs:
      - targets:
        - {{ include "brigade-metrics.exporter.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        labels:
          group: 'exporter'
