apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "brigade-metrics.prometheus.fullname" . }}
  labels:
    {{- include "brigade-metrics.labels" . | nindent 4 }}
    {{- include "brigade-metrics.prometheus.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "brigade-metrics.selectorLabels" . | nindent 6 }}
      {{- include "brigade-metrics.prometheus.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "brigade-metrics.selectorLabels" . | nindent 8 }}
        {{- include "brigade-metrics.prometheus.labels" . | nindent 8 }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/prometheus/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: prometheus
        image: {{ .Values.prometheus.image.repository }}:{{ default .Chart.AppVersion .Values.prometheus.image.tag }}
        imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
        ports:
        - containerPort: 9090
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus/"
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/
        - name: data
          mountPath: /prometheus/
      volumes:
      - name: prometheus-config-volume
        configMap:
          name: {{ include "brigade-metrics.prometheus.fullname" . }}
      - name: data
        {{- if .Values.prometheus.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "brigade-metrics.prometheus.fullname" . }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      {{- with .Values.prometheus.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.prometheus.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
