{{- if .Values.prometheus.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: {{ include "brigade-metrics.prometheus.fullname" . }}
  labels:
    {{- include "brigade-metrics.labels" . | nindent 4 }}
    {{- include "brigade-metrics.prometheus.labels" . | nindent 4 }}
spec:  
  storageClassName: {{ .Values.prometheus.persistence.storageClass }}
  accessModes:
   - {{ .Values.prometheus.persistence.accessMode }}
  resources:
   requests:   
     storage: {{ .Values.prometheus.persistence.size }}
{{- end }}
