{
 "title": "Brigade",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Projects",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "brigade_projects_total" }
   ]
  },
  {
   "title": "Events Counts by Worker Phase",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 18, "h": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "brigade_all_workers_by_phase", "legendFormat": "{{ workerPhase }}" }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "x": 0, "y": 6, "w": 6, "h": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "brigade_users_total" }
   ]
  },
  {
   "title": "Pending Workloads",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 6, "w": 18, "h": 12 },
   "targets": [
    {
     "expr": "brigade_all_workers_by_phase{workerPhase=\"PENDING\"}",
     "legendFormat": "Workers"
    },
    { "expr": "brigade_pending_jobs_total", "legendFormat": "Jobs" }
   ]
  },
  {
   "title": "Service Accounts",
   "type": "stat",
   "gridPos": { "x": 0, "y": 12, "w": 6, "h": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "brigade_service_accounts_total" }
   ]
  }
 ]
}