apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "brigade-metrics.grafana.fullname" . }}-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "brigade-metrics.labels" . | nindent 4 }}
    {{- include "brigade-metrics.grafana.labels" . | nindent 4 }}
data:
  datasources.yaml: |-
    apiVersion: 1

    datasources:
    - name: Brigade-metrics
      type: prometheus
      access: proxy
      isDefault: true
      url: http://{{ include "brigade-metrics.prometheus.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
