apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brigade-metrics.grafana.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "brigade-metrics.labels" . | nindent 4 }}
    {{- include "brigade-metrics.grafana.labels" . | nindent 4 }}
stringData:
  {{- if .Values.grafana.auth.password }}
  password: {{ .Values.grafana.auth.password }}
  {{- else }}
    {{ fail "Value MUST be specified for grafana.auth.password" }}
  {{- end }}
