apiVersion: v1
kind: Service
metadata:
  name: {{ include "brigade-metrics.grafana.fullname" . }}
  labels:
    {{- include "brigade-metrics.labels" . | nindent 4 }}
    {{- include "brigade-metrics.grafana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
  {{- if .Values.grafana.tls.enabled }}
  - port: 443
    targetPort: 443
  {{- else }}
  - port: 80
    targetPort: 80
  {{- end }}
    {{- if and (or (eq .Values.grafana.service.type "NodePort") (eq .Values.grafana.service.type "LoadBalancer")) .Values.grafana.service.nodePort}}
    nodePort: {{ .Values.grafana.service.nodePort }}
    {{- end }}
    protocol: TCP
  selector:
    {{- include "brigade-metrics.selectorLabels" . | nindent 8 }}
    {{- include "brigade-metrics.grafana.labels" . | nindent 8 }}
